class ExplorePlace {
  final String nameVi;
  final String nameEn;
  final String locationVi;
  final String locationEn;
  final String category;
  final String descriptionVi;
  final String descriptionEn;
  final String emoji;

  const ExplorePlace({
    required this.nameVi,
    required this.nameEn,
    required this.locationVi,
    required this.locationEn,
    required this.category,
    required this.descriptionVi,
    required this.descriptionEn,
    required this.emoji,
  });

  String name(String languageCode) {
    return languageCode == 'en' ? nameEn : nameVi;
  }

  String location(String languageCode) {
    return languageCode == 'en' ? locationEn : locationVi;
  }

  String description(String languageCode) {
    return languageCode == 'en' ? descriptionEn : descriptionVi;
  }
}

const explorePlaces = <ExplorePlace>[
  ExplorePlace(
    nameVi: 'Phố cổ Hội An',
    nameEn: 'Hội An Ancient Town',
    locationVi: 'Quảng Nam, Việt Nam',
    locationEn: 'Quảng Nam, Vietnam',
    category: 'heritage',
    descriptionVi: 'Phố cổ Hội An nổi bật với kiến trúc truyền thống, những con phố nhỏ, đèn lồng và dấu ấn giao thương quốc tế.',
    descriptionEn: 'Hội An Ancient Town is known for traditional architecture, lantern-lit streets and its historic international trading heritage.',
    emoji: '\u{1F3EE}',
  ),
  ExplorePlace(
    nameVi: 'Đại Nội Huế',
    nameEn: 'Imperial City of Huế',
    locationVi: 'Huế, Việt Nam',
    locationEn: 'Huế, Vietnam',
    category: 'heritage',
    descriptionVi: 'Đại Nội Huế là trung tâm của quần thể di tích cố đô, gắn với triều Nguyễn và nhiều công trình cung đình đặc sắc.',
    descriptionEn: 'The Imperial City of Huế is the historic center of the former imperial capital and is closely connected to the Nguyễn Dynasty.',
    emoji: '\u{1F3EF}',
  ),
  ExplorePlace(
    nameVi: 'Tràng An',
    nameEn: 'Tràng An',
    locationVi: 'Ninh Bình, Việt Nam',
    locationEn: 'Ninh Bình, Vietnam',
    category: 'nature',
    descriptionVi: 'Tràng An nổi tiếng với cảnh quan núi đá vôi, sông nước và hệ thống hang động tạo nên một không gian thiên nhiên đặc sắc.',
    descriptionEn: 'Tràng An is famous for limestone karsts, waterways and cave systems that create a distinctive natural landscape.',
    emoji: '\u{26F0}\u{FE0F}',
  ),
  ExplorePlace(
    nameVi: 'Thánh địa Mỹ Sơn',
    nameEn: 'Mỹ Sơn Sanctuary',
    locationVi: 'Quảng Nam, Việt Nam',
    locationEn: 'Quảng Nam, Vietnam',
    category: 'culture',
    descriptionVi: 'Thánh địa Mỹ Sơn là quần thể đền tháp Chăm Pa mang giá trị nổi bật về lịch sử, kiến trúc và tín ngưỡng.',
    descriptionEn: 'Mỹ Sơn Sanctuary is a complex of Champa temples with major historical, architectural and religious value.',
    emoji: '\u{1F6D5}',
  ),
  ExplorePlace(
    nameVi: 'Văn Miếu - Quốc Tử Giám',
    nameEn: 'Temple of Literature',
    locationVi: 'Hà Nội, Việt Nam',
    locationEn: 'Hanoi, Vietnam',
    category: 'culture',
    descriptionVi: 'Văn Miếu - Quốc Tử Giám là biểu tượng của truyền thống hiếu học và lịch sử giáo dục lâu đời của Việt Nam.',
    descriptionEn: 'The Temple of Literature represents Vietnam’s long-standing tradition of scholarship and education.',
    emoji: '\u{1F3DB}\u{FE0F}',
  ),
  ExplorePlace(
    nameVi: 'Bảo tàng Mỹ thuật Việt Nam',
    nameEn: 'Vietnam National Fine Arts Museum',
    locationVi: 'Hà Nội, Việt Nam',
    locationEn: 'Hanoi, Vietnam',
    category: 'art',
    descriptionVi: 'Bảo tàng trưng bày nhiều tác phẩm tiêu biểu của mỹ thuật Việt Nam từ truyền thống đến hiện đại.',
    descriptionEn: 'The museum presents notable works of Vietnamese art from traditional periods through modern times.',
    emoji: '\u{1F3A8}',
  ),
  ExplorePlace(
    nameVi: 'Vịnh Hạ Long',
    nameEn: 'Hạ Long Bay',
    locationVi: 'Quảng Ninh, Việt Nam',
    locationEn: 'Quảng Ninh, Vietnam',
    category: 'nature',
    descriptionVi: 'Vịnh Hạ Long gây ấn tượng với hàng nghìn đảo đá vôi, mặt nước rộng lớn và cảnh quan biển đặc trưng.',
    descriptionEn: 'Hạ Long Bay is renowned for its limestone islands, broad seascape and dramatic coastal scenery.',
    emoji: '\u{1F30A}',
  ),
  ExplorePlace(
    nameVi: 'Phong Nha - Kẻ Bàng',
    nameEn: 'Phong Nha - Kẻ Bàng',
    locationVi: 'Quảng Trị, Việt Nam',
    locationEn: 'Quảng Trị, Vietnam',
    category: 'nature',
    descriptionVi: 'Khu vực nổi bật với hệ thống hang động, núi đá vôi và cảnh quan rừng nhiệt đới hùng vĩ.',
    descriptionEn: 'The area is known for extensive cave systems, limestone mountains and impressive tropical forest landscapes.',
    emoji: '\u{1F3DE}\u{FE0F}',
  ),
  ExplorePlace(
    nameVi: 'Fansipan',
    nameEn: 'Fansipan',
    locationVi: 'Lào Cai, Việt Nam',
    locationEn: 'Lào Cai, Vietnam',
    category: 'nature',
    descriptionVi: 'Fansipan là đỉnh núi nổi tiếng của dãy Hoàng Liên Sơn, thu hút du khách bởi cảnh quan núi cao và khí hậu đặc trưng.',
    descriptionEn: 'Fansipan is a famous peak in the Hoàng Liên Sơn range, attracting visitors with high-mountain scenery and a distinctive climate.',
    emoji: '\u{1F3D4}\u{FE0F}',
  ),
  ExplorePlace(
    nameVi: 'Thác Bản Giốc',
    nameEn: 'Bản Giốc Waterfall',
    locationVi: 'Cao Bằng, Việt Nam',
    locationEn: 'Cao Bằng, Vietnam',
    category: 'nature',
    descriptionVi: 'Thác Bản Giốc nổi bật với nhiều tầng nước đổ giữa khung cảnh núi đá và đồng ruộng vùng biên.',
    descriptionEn: 'Bản Giốc Waterfall features cascading tiers set among limestone mountains and rural border landscapes.',
    emoji: '\u{1F4A6}',
  ),
  ExplorePlace(
    nameVi: 'Hồ Ba Bể',
    nameEn: 'Ba Bể Lake',
    locationVi: 'Thái Nguyên, Việt Nam',
    locationEn: 'Thái Nguyên, Vietnam',
    category: 'nature',
    descriptionVi: 'Hồ Ba Bể mang vẻ đẹp yên bình với mặt hồ xanh, rừng núi và đời sống cộng đồng địa phương.',
    descriptionEn: 'Ba Bể Lake offers a peaceful landscape of green water, forested mountains and local community life.',
    emoji: '\u{1F6F6}',
  ),
  ExplorePlace(
    nameVi: 'Hoàng thành Thăng Long',
    nameEn: 'Imperial Citadel of Thăng Long',
    locationVi: 'Hà Nội, Việt Nam',
    locationEn: 'Hanoi, Vietnam',
    category: 'heritage',
    descriptionVi: 'Hoàng thành Thăng Long lưu giữ nhiều dấu tích khảo cổ và kiến trúc gắn với lịch sử lâu dài của kinh đô Thăng Long.',
    descriptionEn: 'The Imperial Citadel of Thăng Long preserves archaeological and architectural traces linked to the long history of the ancient capital.',
    emoji: '\u{1F3F0}',
  ),
  ExplorePlace(
    nameVi: 'Thành nhà Hồ',
    nameEn: 'Hồ Dynasty Citadel',
    locationVi: 'Thanh Hóa, Việt Nam',
    locationEn: 'Thanh Hóa, Vietnam',
    category: 'heritage',
    descriptionVi: 'Thành nhà Hồ gây ấn tượng bởi kỹ thuật xây thành đá quy mô lớn và giá trị lịch sử của một giai đoạn chuyển tiếp.',
    descriptionEn: 'The Hồ Dynasty Citadel is notable for its large-scale stone construction and the history of a transitional period.',
    emoji: '\u{1F9F1}',
  ),
  ExplorePlace(
    nameVi: 'Dinh Độc Lập',
    nameEn: 'Independence Palace',
    locationVi: 'TP. Hồ Chí Minh, Việt Nam',
    locationEn: 'Ho Chi Minh City, Vietnam',
    category: 'heritage',
    descriptionVi: 'Dinh Độc Lập là công trình lịch sử nổi bật của TP. Hồ Chí Minh với kiến trúc hiện đại và nhiều dấu mốc quan trọng.',
    descriptionEn: 'Independence Palace is a major historical landmark in Ho Chi Minh City, known for modern architecture and significant historical events.',
    emoji: '\u{1F3DB}\u{FE0F}',
  ),
  ExplorePlace(
    nameVi: 'Địa đạo Củ Chi',
    nameEn: 'Củ Chi Tunnels',
    locationVi: 'TP. Hồ Chí Minh, Việt Nam',
    locationEn: 'Ho Chi Minh City, Vietnam',
    category: 'heritage',
    descriptionVi: 'Địa đạo Củ Chi là hệ thống công trình ngầm gắn với lịch sử chiến tranh và đời sống chiến đấu trong lòng đất.',
    descriptionEn: 'The Củ Chi Tunnels are an underground network associated with wartime history and life beneath the ground.',
    emoji: '\u{26CF}\u{FE0F}',
  ),
  ExplorePlace(
    nameVi: 'Chùa Một Cột',
    nameEn: 'One Pillar Pagoda',
    locationVi: 'Hà Nội, Việt Nam',
    locationEn: 'Hanoi, Vietnam',
    category: 'culture',
    descriptionVi: 'Chùa Một Cột là công trình tôn giáo nhỏ nhưng có hình thức kiến trúc đặc biệt và là biểu tượng quen thuộc của Hà Nội.',
    descriptionEn: 'The One Pillar Pagoda is a compact religious monument with distinctive architecture and a familiar symbol of Hanoi.',
    emoji: '\u{1F54D}',
  ),
  ExplorePlace(
    nameVi: 'Chợ nổi Cái Răng',
    nameEn: 'Cái Răng Floating Market',
    locationVi: 'Cần Thơ, Việt Nam',
    locationEn: 'Can Tho, Vietnam',
    category: 'culture',
    descriptionVi: 'Chợ nổi Cái Răng phản ánh nét sinh hoạt sông nước đặc trưng của miền Tây Nam Bộ.',
    descriptionEn: 'Cái Răng Floating Market reflects the river-based trading culture of the Mekong Delta.',
    emoji: '\u{1F6F6}',
  ),
  ExplorePlace(
    nameVi: 'Làng gốm Bát Tràng',
    nameEn: 'Bát Tràng Pottery Village',
    locationVi: 'Hà Nội, Việt Nam',
    locationEn: 'Hanoi, Vietnam',
    category: 'culture',
    descriptionVi: 'Bát Tràng nổi tiếng với nghề gốm lâu đời, không gian làng nghề và nhiều sản phẩm thủ công đặc trưng.',
    descriptionEn: 'Bát Tràng is known for its long pottery tradition, craft village atmosphere and distinctive handmade ceramics.',
    emoji: '\u{1F3FA}',
  ),
  ExplorePlace(
    nameVi: 'Làng tranh Đông Hồ',
    nameEn: 'Đông Hồ Folk Painting Village',
    locationVi: 'Bắc Ninh, Việt Nam',
    locationEn: 'Bắc Ninh, Vietnam',
    category: 'art',
    descriptionVi: 'Làng tranh Đông Hồ gắn với dòng tranh dân gian nổi tiếng, kỹ thuật in khắc gỗ và màu sắc truyền thống.',
    descriptionEn: 'Đông Hồ village is associated with a well-known folk painting tradition using woodblock printing and traditional pigments.',
    emoji: '\u{1F5BC}\u{FE0F}',
  ),
  ExplorePlace(
    nameVi: 'Bảo tàng Điêu khắc Chăm',
    nameEn: 'Museum of Cham Sculpture',
    locationVi: 'Đà Nẵng, Việt Nam',
    locationEn: 'Da Nang, Vietnam',
    category: 'art',
    descriptionVi: 'Bảo tàng lưu giữ nhiều tác phẩm điêu khắc Chăm, giúp du khách tìm hiểu nghệ thuật và tín ngưỡng Chăm Pa.',
    descriptionEn: 'The museum preserves an important collection of Cham sculpture, offering insight into Champa art and beliefs.',
    emoji: '\u{1F5FF}',
  ),
  ExplorePlace(
    nameVi: 'Bảo tàng Mỹ thuật TP. Hồ Chí Minh',
    nameEn: 'Ho Chi Minh City Museum of Fine Arts',
    locationVi: 'TP. Hồ Chí Minh, Việt Nam',
    locationEn: 'Ho Chi Minh City, Vietnam',
    category: 'art',
    descriptionVi: 'Bảo tàng giới thiệu nhiều tác phẩm hội họa, điêu khắc và mỹ thuật hiện đại trong một công trình kiến trúc nổi bật.',
    descriptionEn: 'The museum features painting, sculpture and modern Vietnamese art inside a distinctive historic building.',
    emoji: '\u{1F3A8}',
  ),
  ExplorePlace(
    nameVi: 'Nhà hát Lớn Hà Nội',
    nameEn: 'Hanoi Opera House',
    locationVi: 'Hà Nội, Việt Nam',
    locationEn: 'Hanoi, Vietnam',
    category: 'art',
    descriptionVi: 'Nhà hát Lớn Hà Nội là công trình biểu diễn nghệ thuật nổi bật với kiến trúc cổ điển và vị trí trung tâm thành phố.',
    descriptionEn: 'Hanoi Opera House is a prominent performing arts venue known for classical architecture and a central city location.',
    emoji: '\u{1F3AD}',
  ),
  ExplorePlace(
    nameVi: 'Nhà hát Thành phố Hồ Chí Minh',
    nameEn: 'Saigon Opera House',
    locationVi: 'TP. Hồ Chí Minh, Việt Nam',
    locationEn: 'Ho Chi Minh City, Vietnam',
    category: 'art',
    descriptionVi: 'Nhà hát Thành phố là điểm biểu diễn nghệ thuật và một công trình kiến trúc nổi bật ở trung tâm TP. Hồ Chí Minh.',
    descriptionEn: 'The Saigon Opera House is a performing arts venue and a prominent architectural landmark in central Ho Chi Minh City.',
    emoji: '\u{1F3AD}',
  ),
  ExplorePlace(
    nameVi: 'Cầu Vàng',
    nameEn: 'Golden Bridge',
    locationVi: 'Đà Nẵng, Việt Nam',
    locationEn: 'Da Nang, Vietnam',
    category: 'art',
    descriptionVi: 'Cầu Vàng gây ấn tượng với thiết kế bàn tay nâng cầu và góc nhìn rộng ra vùng núi Bà Nà.',
    descriptionEn: 'Golden Bridge is known for its giant hand supports and panoramic views over the Bà Nà mountain area.',
    emoji: '\u{1F309}',
  ),
];
